# Generated by Django 5.1.3 on 2024-12-06 15:33

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='products',
            name='type',
        ),
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Product Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default=datetime.datetime(2024, 12, 6, 15, 33, 14, 894511, tzinfo=datetime.timezone.utc), verbose_name='Product Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.URLField(default=datetime.datetime(2024, 12, 6, 15, 33, 47, 507212, tzinfo=datetime.timezone.utc), verbose_name='Product Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Product Updated'),
        ),
    ]
